/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MyGradleProject;

import java.util.Scanner;

public class Library {
  /*  public boolean someLibraryMethod() {
        return true;
    }*/
	public static void main(String args[]) {
		Scanner sc=new Scanner(System.in);
		System.out.println("enter first number");
		int a=sc.nextInt();
		System.out.println("enter second number");
		int b=sc.nextInt();
		System.out.println("sum of the numbers is:"+(a+b));
}
}
